# Generated by Django 6.0.1 on 2026-02-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_server_balance_server_is_active_server_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
