# Generated by Django 6.0.1 on 2026-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0003_alter_server_username'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['username'], name='user_btree_idx'),
        ),
    ]
