# Generated by Django 6.0.1 on 2026-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_server_user_btree_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
